### PR TITLE
Add term tags to `{tags}` Anki field

### LINKED ISSUE #1454: {tags} handlebar doesnt return term tags
Hi, is there a way to add the frequency info ("ichi" and "news1k") to the card? I tried both "tags" and all five "frequency" values, but neither of them have this info. Btw, frequency rank and frequency occurance values return `0` or `99999`, which, I guess, are wrong 

image
image

### PR DESCRIPTION
**Pull request by khaitruong922**
Fixes #1454

### CODE REVIEW

**Comment by MarvNC** [comment]
Maybe it should be a separate handlebar?

**Comment by khaitruong922** [comment]
> Maybe it should be a separate handlebar?

We can expose the `definition.termTags` as a separate handlebar. If people only want to have either type of tags then it can be useful but I think it's kinda overkill and may cause confusion between `{term-tags}` and `{definition-tags}`.

@Kuuuube thoughts?

**Comment by Kuuuube** [comment]
Best to avoid renaming existing handlebars if it can be avoided. Not sure what the use case for the current tags is to know if this matters.

**Comment by khaitruong922** [comment]
Current {tags} field only returns tags from term definitions (for example `n`, `v5`, `abbr`) but not the tags of the term itself (mostly  from JMDict) like `news20k`, `ichi`, rare tag, high priority term tag, etc.

Currently there is no handlebar to retrieve the term tags, so I add those into the {tags} anki field. I think use cases which requires a separate handlebar are quite limited.

**Review by Casheeew — APPROVED** [review]

**Comment by jamesmaa** [comment]
@Kuuuube could you approve if you feel like PR is mergeable?

I feel like if we think `{tags}` should include both term and definition tags, then let's not worry about existing user expectations and [Hyrum's Law](https://www.hyrumslaw.com/) we really don't have an API contract with our users nor a way to roll out these changes without violating user behaviors sometimes. I don't think that should stop up from doing the right thing if we believe it's the right thing

**Comment by stephenmk** [comment]
Term tags serve a different purpose than definition tags. The term tags are displayed once at the top of a yomitan term, and there could be one or many different sets of definition tags displayed underneath. I'm not sure how exactly this new setup works (nobody has posted anki screenshots), but if the term tags are repeated in each of these definition tag sets, I imagine it would look very cluttered and I expect many users would be unhappy.

**Comment by Kuuuube** [comment]
I'm fine with it as long as it works as it is said (tests look fine). I haven't had the chance to test this myself.

As for users depending on this, this is for sure one of the least used handlebars we have. I've never seen anyone use it.

**Pull request merged**
