### PR TITLE
ExtensionError when validating dictionary includes error cause

### PR DESCRIPTION
**Pull request by austinyu12**
#1019 
Before, it only stated where the ExtensionError occurred.

Before
Screenshot 2024-10-08 at 11 12 29 PM

After
Screenshot 2024-10-08 at 11 12 37 PM

### CODE REVIEW

**Comment by MarvNC** [comment]
Can you edit a screenshot into the post comment

**Comment by austinyu12** [comment]
I decided to throw the `ExtensionError` with all of the information contained within `schema.errors`. I attempted only returning the `message` property of `schema.errors`, but I decided against it. The code was already simple and will mainly be used for developers, so didn't seem like a problem if it contained a little bit of extra information, though if anyone has any idea on how that can be implemented, I would appreciate it. It also seems to be failing performance benchmarks.

**Comment by Casheeew** [comment]
> It also seems to be failing performance benchmarks. 

The benchmarking tool that we use was affected by the organizational move, so it is not working at the moment.

**Review by Casheeew — APPROVED** [review]

**Comment by djahandarie** [comment]
Hmm, ExtensionError doesn't support HTML internally right? It would probably be nice to format just the JSON with a monospace font (so that people know they can just skim over it, esp if they are not technical), but I guess that's not easy to accomplish with the current error type

**Comment by austinyu12** [comment]
> ExtensionError doesn't support HTML internally right?
`ExtensionError` seems to just extend `Error`. From what I can tell, I doesn't interact with the DOM directly.

**Review by jamesmaa — APPROVED** [review]

**Pull request merged**
