### PR TITLE
Force scan resolution "character" for ja, zh, yue, and ko

### PR DESCRIPTION
**Pull request by Kuuuube**
Also hides the option from settings for these languages and splits out the visibility modifiers.

Addresses https://github.com/yomidevs/yomitan/pull/1368#pullrequestreview-2387006730

### CODE REVIEW

**Comment by jamesmaa** [comment]
Wouldn't this be better enforced by enforcing jazhyueko to have the `scanResolution` setting to be `character`?

**Comment by Kuuuube** [comment]
As in setting the variable to that in the text scanner when options are passed through? That would be fine. Actually changing the setting set by the user I'd rather not do that though.

**Comment by MarvNC** [comment]
> Actually changing the setting set by the user I'd rather not do that though.

Why? For those languages it makes sense, and it seems like it'd be easier to maintain than having to find a const in text-scanner.

**Comment by Kuuuube** [comment]
Just feels wrong. The user changed one setting (language) and it automatically changed a setting they didnt intend to change.

**Review by jamesmaa — APPROVED** [review]
I think this solution should be more generalizable but I haven't come up with future use cases just yet so i don't think it's worth having an inferior user experience while waiting for said generalized solution.

**Review by jamesmaa — APPROVED** [review]

**Pull request merged**
