### PR TITLE
french de-inflection

### LINKED ISSUE #1572: [French]: French de-inflection logic
We currently don't have any support for French de-inflection logic. If anyone is willing to do it that would be très bien ❤️

### PR DESCRIPTION
**Pull request by SalwynnJP**
This is a draft
Resolves #1572 

If there is anything missing or any typo errors (although I think it's already quite complete), you can refer to the Bescherelle for verification.
https://ia801304.us.archive.org/8/items/BescherelleLaConjugaisonPourTous/bescherelle%20la%20conjugaison%20pour%20tous.pdf

### CODE REVIEW

**Comment by impucky** [comment]
Commenting here since it was mentioned. 
What's needed exactly, a look over of all the added de-inflection rules?
I'm a French native but I'm not sure I could spot anything that someone with a Bescherelle wouldn't. Happy to take a look though.

**Comment by impucky** [comment]
I checked up until line 3046 (start of prétérit) to the best of my ability, here's what I could spot:

- 50 (ils) ont
- 1295 could all use the y variant?
- 1298 (il) paiera
- 1523 (il) pleuvra, missing (ils) pleuvront? apparently it exists
- 2031, 2032 haïssons, haïssez
- 2284 just a typo on the comment

From line 2324 I think the whole Conditionnel section could use a second pass. 
Sometimes it seems like there might be a mix up with another tense.
A lot of weird stuff especially between 2600-2800

- 2416 I think should all be accent aigu
- 2564 could all use the i variant?
- 2571 I think should all be i instead of y -  j'aboierais, j'essuierais...
- 2608- 2610 viendrions, viendriez, viendraient
- 2613, 2614, 2617 irais, irait, iraient
- 2620 should be irais, irait
- 2627, 2628 êtirais, êtirait
- 2633 vrirais vrirait vririons vririez vriraient
- 2640 frirais, frirait
- 2650 ueillerions, ueilleriez, ueilleraient
- 2655- 2659
- 2661 ?
- 2665 bouillirais, bouillirait
- 2673, 2674, 2677
- 2682, 2683
- 2689, 2690
- 2714 unused in modern French apparently but : gîrais, gîrait, gîraient
- 2721 cevrais cevrait cevrions cevriez cevraient
- 2731 - 2733  verrions verriez verraient
- 2735
- 2759, 2760
- 2788

After that it seems fine again. Stopping here for now because I'm getting tired!

**Comment by SalwynnJP** [comment]
I want to leave you full freedom when it comes to corrections for the de-inflection. I was trying to do a lot quickly, so I didn’t really take the time to proofread carefully.

Of course, feel free to add the past participle and maybe another tense if needed!

I also wanted to say that maybe you could look into something with adjectives, invariable words, etc. as well.

And just so you know, I won’t be doing anything related to computers anymore anyway. I’m focusing on my life now.

**Comment by impucky** [comment]
Okay I understand! 

I can't commit to fully taking over this for now since I have a lot going on (though much of it _is_ computer related), and it will get even busier with the holidays coming up...

I can at least try to get in a first round of corrections sometime soon. 
Anything beyond that like extra tenses, adjectives... maybe January and beyond.
it would be good if someone else can also take a look.

Thanks for your contribution Salwynn, I realized going through it that it's a huge undertaking.
Best of luck with everything, prends soin de toi !

**Pull request closed without merging**
